---
title: "C0 Add Makers and desc_2mine"
output: html_notebook
---
```{r setup, include=FALSE}
# Clear the environment
rm(list = ls())
gc()
# Load required packages to set wd
if (!require("rstudioapi")) install.packages("rstudioapi")
library(rstudioapi)
library(knitr)

# Get the directory of the active document and then move to the parent directory
parent_dir <- dirname(dirname(rstudioapi::getActiveDocumentContext()$path))

# Set the root directory for all chunks to the parent directory
opts_knit$set(root.dir = parent_dir)
```

```{r}
# Verify the working directory in subsequent chunks
getwd()
```

```{r}
source("./Functions/A0 Package Setup.R")
```

```{r}
# Set parameters
source <- "crs"
skip_icov <- TRUE
job_specific_suffix <- "_full_"
current_year <- year(Sys.Date())

# Correct the paths relative to the current working directory
path_input_crs <- paste0("./data/Intermediate/crs01_1", job_specific_suffix, current_year,  ".feather")
path_intermediate_crs_after_cleaning <- paste0("./data/Intermediate/crs02_int_clean_titles", job_specific_suffix, current_year,  ".feather")
path_output_crs <- paste0("./data/Intermediate/crs02.0", job_specific_suffix, current_year, ".feather")

```

```{r}
# Function to print time difference
print_time_diff <- function(start_time) {
  difftime(Sys.time(), start_time, units = "sec") %>% print()
}

```

```{r}
# Start timer
start <- Sys.time()

print(getwd())
# Load the data file
print("Loading document:")
#df_crs_raw <- read_feather(path_input_crs)

# Read the Feather file using arrow
library(arrow)
df_crs_raw <- arrow::read_feather(path_input_crs)

print_time_diff(start)

```

```{r}
# Simplify the working dataset by selecting necessary columns
cols_needed <- c("process_id", 
                 "projecttitle", 
                 "shortdescription", 
                 "longdescription", 
                 "purposecode", 
                 "donorname", 
                 "gender", 
                 "channelcode", 
                 "rmnch", 
                 "year")

df_crs_raw <- df_crs_raw %>%
  select(all_of(cols_needed))
beep()

```


```{r}
# Process text data
# Function to clean text
clean_titles <- function(title) {
  title %>%
    removeNumbers() %>%
    removePunctuation(preserve_intra_word_dashes = TRUE) %>%
    tolower()
}


```

```{r}
# Clean and process text data
df_crs <- df_crs_raw %>%
  mutate(
    projecttitle = clean_titles(projecttitle),
    shortdescription = clean_titles(shortdescription),
    longdescription = clean_titles(longdescription),
    longdescription = ifelse(is.na(longdescription) | longdescription == "", shortdescription, longdescription)
  )
print("Cleaned 3 text columns")
print_time_diff(start)
gc()
beep()
```

```{r}
# Reduce longdesc by removing ones too similar to titles
max_string_dist <- 10

df_crs_2detect4diff <- df_crs %>%
  select(projecttitle, longdescription, process_id) %>%
  filter((nchar(projecttitle) - nchar(longdescription))^2 < 900) %>%
  mutate(ldesc_id_tmp = as.numeric(as.factor(paste(projecttitle, longdescription))))

df_crs_2detect4diff_shorten <- df_crs_2detect4diff %>%
  distinct(ldesc_id_tmp, projecttitle, longdescription) %>%
  mutate(desc_2mine = ifelse(stringdist(projecttitle, longdescription) < max_string_dist, NA, longdescription)) %>%
  select(ldesc_id_tmp, desc_2mine)

df_crs_2detect4diff <- df_crs_2detect4diff %>%
  left_join(df_crs_2detect4diff_shorten, by = "ldesc_id_tmp") %>%
  select(process_id, desc_2mine)

df_crs_desc2mine <- df_crs %>%
  mutate(desc_2mine = longdescription) %>%
  select(process_id, desc_2mine) %>%
  filter(!(process_id %in% df_crs_2detect4diff$process_id)) %>%
  bind_rows(df_crs_2detect4diff) %>%
  mutate(desc_2mine_id = as.numeric(as.factor(desc_2mine)))

df_crs <- df_crs %>%
  left_join(df_crs_desc2mine, by = "process_id") %>%
  mutate(text_id = desc_2mine_id)

df_crs <- df_crs %>% 
 mutate(title_id = as.numeric(as.factor(tolower(projecttitle))))
```

```{r}
# Save intermediate cleaned data
write_feather(df_crs, path_intermediate_crs_after_cleaning)


# Clean up
rm(df_crs_2detect4diff_shorten, df_crs_2detect4diff)
gc()
print("Found the best text for desc_2mine and saved cleaned data")
print_time_diff(start)
```
```{r}
#Add markers from PP code and policy markers
start <- Sys.time()

df_crs <- df_crs %>%
  mutate(
    scb = ifelse(purposecode == 16062, 1, 0),
    pop = ifelse(purposecode == 13010, 1, 0),
    gen_ppcode = purposecode %in% c(15170:15180),
    gen_donor = channelcode == 41146,
    gen_marker = gender %in% c(1, 2) & !is.na(gender),
    gen_marker1 = gender == 1,
    gen_marker2 = gender == 2,
    gen_rmnch = rmnch %in% c(1, 2),
    gen_rmnch1 = rmnch == 1,
    gen_rmnch2 = rmnch == 2,
    mining_ppcode = purposecode == 15250
  )

```

```{r}
#RMNCH Analysis
table(df_crs$rmnch)
```

```{r}
#Language Detection
# Select relevant columns and drop duplicates
df_crs_lang <- df_crs %>%
  select(text_id, desc_2mine) %>%
  filter(!duplicated(text_id)) %>%
  mutate(language = cld2::detect_language(desc_2mine)) %>%
  select(-desc_2mine)

df_crs_lang_title <- df_crs %>%
  select(title_id, projecttitle) %>%
  distinct() %>%
  mutate(language_title = cld2::detect_language(projecttitle)) %>%
  select(-projecttitle)

print("Detecting Language")
print_time_diff(start)
beep()

```


```{r}
#Join with Raw Data
# Keep only necessary columns
vec_cols_2keep <- setdiff(names(df_crs), names(df_crs_raw))

df_crs <- df_crs %>%
  select(process_id, all_of(vec_cols_2keep)) %>%
  right_join(df_crs_raw, by = "process_id") %>%
  select(-longdescription) %>%
  left_join(df_crs_lang, by = "text_id") %>%
  left_join(df_crs_lang_title, by = "title_id") %>%
  mutate(language_desc = language)
```

```{r}
#Clean Up
rm(df_crs_lang, df_crs_lang_title, df_crs_raw)
print("Rest of the analysis")
print_time_diff(start)
gc()
Sys.sleep(10)

```

```{r}
#Analysis Summary
print("NAs in desc_2mine")
length(which(is.na(df_crs$desc_2mine) | df_crs$desc_2mine == "")) %>% print()
table(df_crs$language) %>% print()
names(df_crs) %>% print()
print_time_diff(start)

```

```{r}
#Save Processed Data
start <- Sys.time()
write_feather(df_crs, path_output_crs)
print("Save file:")
print(path_output_crs)
print_time_diff(start)
beep()
```

